title: Authority
description: Authority helps you authorize actions in your Rails app. It's ORM-neutral and has very little fancy syntax; just group your models under one or more Authorizer classes and write plain Ruby methods on them.
google_analytics: UA-40553084-1
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
